# Generated by Django 5.2.11 on 2026-05-08 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('periodo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_dorado', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=300)),
                ('texto', models.TextField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='core.era')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres', to='core.era')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.era')),
            ],
        ),
        migrations.CreateModel(
            name='Victoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victorias', to='core.era')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
