# Generated by Django 5.2.13 on 2026-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('organizacion', models.CharField(max_length=200)),
                ('guerreros', models.CharField(max_length=300)),
                ('metodo', models.CharField(choices=[('Persuasión', 'Persuasión'), ('Infiltración', 'Infiltración'), ('Engaño', 'Engaño'), ('Trampa', 'Trampa'), ('Oferta monetaria', 'Oferta monetaria')], max_length=50)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
    ]
