# Generated by Django 5.2.13 on 2026-05-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conquista'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='multimedia/fotos/')),
                ('anio', models.IntegerField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', '-anio'],
            },
        ),
        migrations.CreateModel(
            name='VideoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', '-anio'],
            },
        ),
    ]
