# Generated by Django 5.2.13 on 2026-05-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fotomultimedia_videomultimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=20)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'numero'],
            },
        ),
    ]
